spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: '4.0'

cards:
  message: "Welcome to Easy Bank Accounts related API's"
  contactDetails:
    name: Naveen - Prod Support Manager"
    email: naveen.gaddam@cirium.com"
  onCallSupport:
    - (+91) 73067 11886
    - (+91) 93905 84040



